import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

 function Home() {
  const router = useRouter()

  const handleClick = () => {
    router.push('/product/1')
    // router.replace('/product')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        header
      </header>

      <main>
        main
      </main>

      <footer>
        footer
      </footer>

      <button onClick={handleClick}>Click Here then navigate Product</button>
    </div>
  )
}
export default Home
